"""Add is_admin to Sharpener and cancel fields to Ticket

Revision ID: 6a57427d97ed
Revises: a1b2c3d4e5f6
Create Date: 2026-01-04 21:21:19.641721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '6a57427d97ed'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c['name'] for c in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # Add is_admin to sharpener if not exists
    if not column_exists('sharpener', 'is_admin'):
        with op.batch_alter_table('sharpener', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # Add cancel fields to ticket if not exists
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        if not column_exists('ticket', 'cancelled_at'):
            batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        if not column_exists('ticket', 'cancelled_by_id'):
            batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_ticket_cancelled_by', 'sharpener', ['cancelled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_cancelled_by', type_='foreignkey')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('cancelled_at')

    with op.batch_alter_table('sharpener', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
